# Generated by Django 5.0.3 on 2024-03-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_medicalvisit_hospital_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalvisit',
            name='mensuration_AV_OD',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='medicalvisit',
            name='mensuration_OG',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='medicalvisit',
            name='mensuration_PA',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='medicalvisit',
            name='mensuration_PIT',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='medicalvisit',
            name='mensuration_PTE',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='medicalvisit',
            name='mensuration_Pouls',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='medicalvisit',
            name='mensuration_TA',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='medicalvisit',
            name='mensuration_kg',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='medicalvisit',
            name='mensuration_size',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
