# Generated by Django 5.0.3 on 2024-03-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_medicalvisit_mensuration_av_od_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Doctor', 'Doctor'), ('Nurse', 'Nurse')], default='Admin', max_length=10),
        ),
    ]
