# Generated by Django 5.0.3 on 2024-03-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugs',
            name='drug_type',
            field=models.CharField(choices=[('Tablet', 'Tablet'), ('Capsule', 'Capsule'), ('Liquid', 'Liquid'), ('Injection', 'Injection'), ('Cream', 'Cream'), ('Spray', 'Spray')], default='Tablet', max_length=20),
        ),
    ]
