# Generated by Django 5.0.3 on 2024-03-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_alter_patient_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='picture',
            field=models.ImageField(blank=True, upload_to='img/'),
        ),
    ]
