# Generated by Django 5.0.3 on 2024-03-27 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_alter_patient_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='date_of_birth',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='name',
            new_name='birth_place',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='patient_creation_date',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='num_dependent_children',
            new_name='dependent_children',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='place_of_birth',
            new_name='employee_name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='reason_for_leaving',
            new_name='leaving_reason',
        ),
    ]
