# Generated by Django 5.0.3 on 2024-03-28 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_rename_date_of_birth_patient_birth_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='enterprise_name',
            new_name='enterprise_ID',
        ),
    ]
