# Generated by Django 5.0.3 on 2024-03-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_rename_enterprise_name_patient_enterprise_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='partial_permanent_incapacity',
            field=models.CharField(choices=[('Yes', 'Yes'), ('Not', 'Not')], max_length=5),
        ),
    ]
