# Generated by Django 5.0.3 on 2024-03-30 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_alter_accident_partial_permanent_incapacity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accident',
            old_name='numb_of_days_off',
            new_name='days_off',
        ),
        migrations.RenameField(
            model_name='accident',
            old_name='nature_of_lesions',
            new_name='lesions_nature',
        ),
        migrations.RenameField(
            model_name='accident',
            old_name='causal_material_element',
            new_name='material_causel',
        ),
        migrations.RenameField(
            model_name='accident',
            old_name='partial_permanent_incapacity',
            new_name='partial_incapacity',
        ),
    ]
