# Generated by Django 5.0.3 on 2024-03-30 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_rename_numb_of_days_off_accident_days_off_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occupationalillness',
            old_name='maladie',
            new_name='sickness',
        ),
        migrations.RenameField(
            model_name='occupationalillness',
            old_name='tableau',
            new_name='table',
        ),
    ]
