# Generated by Django 5.0.3 on 2024-03-30 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_rename_maladie_occupationalillness_sickness_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BackgroundPatient',
            new_name='Background',
        ),
    ]
