# Generated by Django 5.0.3 on 2024-03-30 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_rename_backgroundpatient_background'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(max_length=255)),
                ('issue_date', models.DateField()),
                ('summons_date', models.DateField()),
                ('presentation_date', models.DateField()),
                ('observation', models.TextField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.patient', to_field='employee_id')),
            ],
        ),
        migrations.DeleteModel(
            name='SummonsForm',
        ),
    ]
