# Generated by Django 5.0.3 on 2024-04-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0020_alter_appointment_appointment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='efectifs',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
    ]
