# Generated by Django 5.0.3 on 2024-04-04 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0021_schedule_efectifs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='efectifs',
            new_name='patient_limite',
        ),
    ]
