# Generated by Django 5.0.3 on 2024-04-04 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0022_rename_efectifs_schedule_patient_limite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='patient_limite',
            new_name='patient_limit',
        ),
    ]
