# Generated by Django 5.0.3 on 2024-04-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0023_rename_patient_limite_schedule_patient_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='from_time',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='to_time',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=20),
        ),
    ]
