# Generated by Django 5.0.3 on 2024-04-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0024_remove_schedule_from_time_remove_schedule_to_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='from_time',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='to_time',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
    ]
