# Generated by Django 5.0.3 on 2024-04-08 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0025_schedule_from_time_schedule_to_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_time',
            new_name='time',
        ),
    ]
